---

- name: preconfigure all linux nodes
  hosts: "tag_app_sap_hana_ha_demo:!tag_role_sapgui"

  roles:
    - storage
    - common
    - redhatinsights.insights.insights_client
  post_tasks:
    - name: run the insights-client and upload to c.rh.c
      shell: insights-client
