---

- name: preconfigure all nodes
  hosts: "tag_app_sap_hana_ha_demo:!tag_role_sapgui"

  roles:
    - sap-preconfigure
    - redhat_sap.sap_rhsm
    - redhat_sap.sap_hostagent

  post_tasks:
    - name: run the insights-client and upload to c.rh.c
      shell: insights-client


- name: preconfigure hana and deploy hana
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana"
  become_method: su

  roles:
    - sap-hana-preconfigure

  post_tasks:
    - name: run the insights-client and upload to c.rh.c
      shell: insights-client

- name: preconfigure netweaver and install s4 app
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_s4app"

  roles:
    - sap-netweaver-preconfigure

  post_tasks:
    - name: run the insights-client and upload to c.rh.c
      shell: insights-client

