---

- name: RHN register
  hosts: "tag_app_sap_hana_ha_demo:!tag_role_sapgui"

  pre_tasks:

    - name: set repos for 7.x
      set_fact:
        repo_channels:
          - rhel-7-server-rpms
          - rhel-7-server-rh-common-rpms
          - rhel-7-server-extras-rpms
          - rhel-7-server-aus-optional-rpms
          - rhel-7-server-optional-rpms
          - rhel-7-server-supplementary-rpms
          - rhel-7-server-ose-3.11-rpms
          - rhel-7-fast-datapath-rpms
          - rhel-7-server-ansible-2.6-rpms
          - rhel-7-server-openstack-14-rpms
          - rhel-7-server-openstack-14-devtools-rpms
          - rhel-7-server-rhv-4.3-manager-rpms
          - rhel-7-server-rhv-4-manager-tools-rpms
          - rhel-7-server-ansible-2-rpms
          - jb-eap-7.2-for-rhel-7-server-rpms
          - rhel-7-server-rhv-4-mgmt-agent-rpms
          - rhel-7-server-ansible-2-rpms
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7

    - name: set repos for 8.x
      set_fact:
        repo_channels:
          - rhel-8-for-x86_64-baseos-rpms
          - rhel-8-for-x86_64-supplementary-rpms
          - rhel-8-for-x86_64-appstream-rpms
          - rhel-8-for-x86_64-highavailability-rpms
          - fast-datapath-for-rhel-8-x86_64-rpms
          - ansible-2.8-for-rhel-8-x86_64-rpms
          - codeready-builder-for-rhel-8-x86_64-rpms
          - advanced-virt-for-rhel-8-x86_64-rpms
          - openstack-16-for-rhel-8-x86_64-rpms
          - openstack-16-tools-for-rhel-8-x86_64-rpms
          - openstack-16-devtools-for-rhel-8-x86_64-rpms
#          - rhv-4-mgmt-agent-beta-for-rhel-8-x86_64-rpms
#          - ansible-2.9-for-rhel-8-x86_64-rpms
#          - advanced-virt-for-rhel-8-x86_64-rpms
#          - rhvh-4-beta-for-rhel-8-x86_64-rpms
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8

  tasks:
    - block:
        - include_role:
            name: oatakan.rhn

      rescue:
        - include_role:
            name: oatakan.rhn
          vars:
            role_action: unregister