- hosts: localhost
  become: no
  gather_facts: no
  vars_files:
    - node-config/nodes-ec2.yml
  roles:
    - ec2-find-amis
    - ansible-role-ec2
    - s3-iam-profile

  post_tasks:
    - name: add hosts to hana group
      add_host:
        name: "{{ item.instances[0].public_ip_address }}"
        ansible_host: "{{ item.instances[0].public_ip_address }}"
        ansible_user: ec2-user
        groups: tag_role_hana,tag_app_sap_hana_ha_demo
      loop: "{{ instances.results }}"
      when:
        - ('sap_hana_ha_demo' in item.instances[0].tags.app)
        - ('hana' in item.instances[0].tags.role)
      changed_when: no

    - name: add hosts to s4app group
      add_host:
        name: "{{ item.instances[0].public_ip_address }}"
        ansible_host: "{{ item.instances[0].public_ip_address }}"
        ansible_user: ec2-user
        groups: tag_role_s4app,tag_app_sap_hana_ha_demo
      loop: "{{ instances.results }}"
      when:
        - ('sap_hana_ha_demo' in item.instances[0].tags.app)
        - ('s4app' in item.instances[0].tags.role)
      changed_when: no

    - name: add hosts to sapgui group
      add_host:
        name: "{{ item.instances[0].public_ip_address }}"
        ansible_host: "{{ item.instances[0].public_ip_address }}"
        ansible_user: Administrator
        ansible_port: 5986
        ansible_password: "{{ service_user_password }}"
        ansible_connection: "{{ windows_ansible_connection | default('winrm') }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
        groups: tag_role_sapgui,tag_app_sap_hana_ha_demo
      loop: "{{ instances.results }}"
      when:
        - service_user_password is defined
        - ('sap_hana_ha_demo' in item.instances[0].tags.app)
        - ('sapgui' in item.instances[0].tags.role)
      changed_when: no

    - name: wait for connection
      wait_for_connection:
      delegate_to: "{{ item.instances[0].public_ip_address }}"
      loop: "{{ instances.results }}"
      when: ('sap_hana_ha_demo' in item.instances[0].tags.app)
      changed_when: no

    - name: enable root login
      replace:
        path: /root/.ssh/authorized_keys
        regexp: '(.*)(ssh-rsa .*)$'
        replace: '\2'
      become: yes
      delegate_to: "{{ item.instances[0].public_ip_address }}"
      loop: "{{ instances.results }}"
      when:
        - ('sap_hana_ha_demo' in item.instances[0].tags.app)
        - ('sapgui' not in item.instances[0].tags.role)
      changed_when: no