- hosts: all
  become: yes

  tasks:
    - shell: whoami
#    - shell: |
#        source /usr/sap/RHE/home/.sapenv.sh && \
#        /usr/sap/RHE/HDB00/exe/hdbsql \
#        -i 00 -u SYSTEM -p {{ sap_password }} -d SYSTEMDB -m <<EOF
#        BACKUP DATA USING FILE ('system_bck');
#        EOF
      args:
        executable: /bin/bash
      register: backup
      become: yes
      become_user: rheadm
      become_method: su
      become_exe: 'sudo su -'
      changed_when: "'0 rows affected' in backup.stdout"


    - debug:
        msg: "{{ backup }}"