- hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana"

  tasks:
    - shell: |
        source /usr/sap/RHE/home/.sapenv.sh && \
        /usr/sap/RHE/HDB00/exe/hdbsql \
        -i 00 -u SYSTEM -p {{ sap_password }} -d SYSTEMDB -m <<EOF
        BACKUP DATA USING FILE ('system_bck');
        EOF
      args:
        executable: /bin/bash
      register: backup
      become: yes
      become_user: rheadm
      become_method: su
      changed_when: "'0 rows affected' in backup.stdout"
      when:
        - sap_hana_hsr_role == 'primary'

    - debug:
        msg: "{{ backup }}"