---

- name: add vip to hosts file for db
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ sap_db_host }}$'
    line: "{{ sap_hana_vip }} {{ sap_db_host }}.{{ domain_name }} {{ sap_db_host }}"
    state: present
  when:
    - sap_db_host is defined
    - sap_hana_vip is defined